
@file:JvmName("UnfoldTransitionFactory")

package com.android.systemui.unfold

import android.content.Context
import android.hardware.SensorManager
import android.hardware.display.DisplayManager
import android.os.Handler
import com.android.systemui.unfold.config.UnfoldTransitionConfig
import com.android.systemui.unfold.updates.FoldProvider
import com.android.systemui.unfold.updates.screen.ScreenStatusProvider
import com.android.systemui.unfold.util.CurrentActivityTypeProvider
import java.util.concurrent.Executor

/**
 * Factory for [UnfoldSharedComponent].
 *
 * This wraps the autogenerated factory (for discoverability), and is needed as Launcher has to
 * create the object manually. If dagger is available, this object is provided in
 * [UnfoldSharedModule].
 *
 * This should **never** be called from sysui, as the object is already provided in that process.
 */
fun createUnfoldSharedComponent(
        context: Context,
        config: UnfoldTransitionConfig,
        screenStatusProvider: ScreenStatusProvider,
        foldProvider: FoldProvider,
        activityTypeProvider: CurrentActivityTypeProvider,
        sensorManager: SensorManager,
        mainHandler: Handler,
        mainExecutor: Executor,
        singleThreadBgExecutor: Executor,
        tracingTagPrefix: String,
        displayManager: DisplayManager,
        bgHandler: Handler,
): UnfoldSharedComponent =
        DaggerUnfoldSharedComponent.factory()
                .create(
                        context,
                        config,
                        screenStatusProvider,
                        foldProvider,
                        activityTypeProvider,
                        sensorManager,
                        mainHandler,
                        mainExecutor,
                        singleThreadBgExecutor,
                        tracingTagPrefix,
                        displayManager,
                        bgHandler,
                )

/**
 * Factory for [RemoteUnfoldSharedComponent].
 *
 * Wraps [DaggerRemoteUnfoldSharedComponent] (that is autogenerated), for better discoverability.
 */
fun createRemoteUnfoldSharedComponent(
        context: Context,
        config: UnfoldTransitionConfig,
        mainExecutor: Executor,
        mainHandler: Handler,
        singleThreadBgExecutor: Executor,
        bgHandler: Handler,
        tracingTagPrefix: String,
        displayManager: DisplayManager,
        ): RemoteUnfoldSharedComponent =
        DaggerRemoteUnfoldSharedComponent.factory()
                .create(
                        context,
                        config,
                        mainExecutor,
                        mainHandler,
                        singleThreadBgExecutor,
                        bgHandler,
                        displayManager,
                        tracingTagPrefix,
                )
