
syntax = "proto2";

option java_package = "com.android.launcher3.logger";
option java_outer_classname = "LauncherAtomExtensions";


// This proto file contains placeholder messages that can be overridden by
// other Launcher variants.
// Variants could have its own launcher_atom_extension.proto file(should have
// same messages declared here but with different implementation); when building
// variant's apk launcher_atom.proto will reference variant's extension file,
// essentially overriding this file.


// Wrapper message for additional containers used in variants.
message ExtendedContainers {}
